version: '3'
services:
  cakemix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakemix
    depends_on:
      - cakemixpg
    links:
      - cakemixpg:5432
    environment:
      DBHOST: cakemixpg
      DBPORT: 5432
      DBUSER: postgres
      DBPASS: postgres
      DBNAME: cakemix
    networks:
      - shared-network

  cakemixpg:
    image: postgres
    container_name: cakemixpg
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  shared-network:
    external: true