version: '3'
services:
  cakemix:
    image: golang
    container_name: cakemixsv
    ports:
      - 8081:8081
    volumes:
      - .:/root/src/github.com/wonder-wonder/cakemix-server
      - ./docker/goweb/go:/go
    command: bash -c "GOPATH=/go:/root && cd /root/src/github.com/wonder-wonder/cakemix-server && make key && make build && ./cakemixsv"
    depends_on:
      - cakemixpg
    links:
      - cakemixpg:5432
    environment:
      DBHOST: cakemixpg
      DBPORT: 5432
      DBUSER: postgres
      DBPASS: postgres
      DBNAME: cakemix

  cakemixpg:
    image: postgres
    container_name: cakemixpg
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres