version: '3'
services:
  cakemix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakemix
    depends_on:
      - cakemixpg
    restart: always
    env_file:
      - sendgrid.env
      - cakemix.env
    volumes:
      - ./dist:/root/dist
      - ./docker/server/cmdat:/root/cmdat
      - ./docker/server/keys:/root/keys
    networks:
      - shared-network
      - cakemix-network

  cakemixpg:
    image: postgres
    container_name: cakemixpg
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - cakemix-network

networks:
  shared-network:
    external: true
  cakemix-network: