version: '3'
services:
  cakemix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakemix
    depends_on:
      - cakemixpg
    links:
      - cakemixpg:5432
    restart: always
    env_file:
      - sendgrid.env
    environment:
      DBHOST: cakemixpg
      DBPORT: 5432
      DBUSER: postgres
      DBPASS: postgres
      DBNAME: cakemix
      FRONTDIR: /root/dist
      DATADIR: /root/cmdat
      SIGNPRVKEY: /root/keys/signkey
      SIGNPUBKEY: /root/keys/signkey.pub
    volumes:
      - ./dist:/root/dist
      - ./docker/server/cmdat:/root/cmdat
      - ./docker/server/keys:/root/keys
    networks:
      - shared-network
      - cakemix-network

  cakemixpg:
    image: postgres
    container_name: cakemixpg
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - cakemix-network

networks:
  shared-network:
    external: true
  cakemix-network: