on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref,'release/')
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: add tag
      run: |
        git checkout master
        git tag ${GITHUB_HEAD_REF#release/}
        git push --tags