name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref,'release/')
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: get new tag
      run: echo "newtag=${GITHUB_HEAD_REF#release/}"" >> $GITHUB_ENV
    - name: add tag
      run: |
        git checkout main
        git tag ${{ env.newtag }}
        git push --tags
    - name: create release
      uses: actions/github-script@0.3.0
      env:
        PRODUCTION_BRANCH: release
        TZ: Asia/Tokyo
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr = context.payload.pull_request

          github.repos.createRelease({
            ...context.repo,
            draft: false,
            tag_name: ${{ env.newtag }},
            name: ${{ env.newtag }},
            target_commitish: process.env.GITHUB_SHA,
            body: pr.body
          });